name = "DependencyWalker"
uuid = "7db386b5-e858-4964-8eb4-2fa66f8df882"
authors = ["Mosè Giordano"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
